config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :users

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :steps
  resources :comments

  resources :plans do
      member do
        get :add_to_calendar
        put :increase_popularity, as: :increase_popularity_of
      end
  end      
  

  get 'pages/info'
  get '/about'    => 'high_voltage/pages#show', id: 'about'
  get '/contact'  => 'high_voltage/pages#show', id: 'contact'
  get '/privacy'  => 'high_voltage/pages#show', id: 'privacy'
  get '/terms'    => 'high_voltage/pages#show', id: 'terms'
  get '/home', to: redirect('/')

  root :to => redirect('/plans')

end

app/models/step.rb
class Step < ActiveRecord::Base
  #searchable do 
  #  text :planstep
  #end

  belongs_to :plan

 	# validates_presence_of :planstep
	# validates_presence_of :plan_id

	# Table name: events
	#
	#  id           :integer(11)     not null, primary key
	#  title        :string(255)
	#  date         :datetime
	#  end_date     :datetime
	#  summary      :text
	#  content      :text
	#  created_at   :datetime
	#  updated_at   :datetime
	
	# # Convert to iCalendar
	# def to_ics
	#   event = Icalendar::Event.new
	#   event.start = self.date.strftime("%Y%m%dT%H%M%S")
	#   event.end = self.end_date.strftime("%Y%m%dT%H%M%S")
	#   event.summary = self.title
	#   event.description = self.summary
	#   event.location = 'Here!'
	#   event.klass = "PUBLIC"
	#   event.created = self.created_at
	#   event.last_modified = self.updated_at
	#   event.uid = event.url = "#{PUBLIC_URL}events/#{self.id}"
	#   event.add_comment("Comment for step of plan")
	#   event
	# end

  def as_indexed_json(options={})
    as_json(only: [:id, :planstep])
  end
      
# Convert to iCalendar
	def to_ics
	  event = Icalendar::Event.new
	  event.start = Date.today
	  event.end = Date.today
	  event.summary = self.planstep
	  event.description = self.planstep
	  event.location = 'Here'
	  event.klass = "PUBLIC"
	  # event.created = self.created_at
	  # event.last_modified = self.updated_at
	  # event.uid = event.url = "#{PUBLIC_URL}events/#{self.plan_id}"
	  event.add_comment("Hardcoded comment")
	  event
	end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_action :set_step, only: [:show, :edit, :update, :destroy]
 skip_before_action :authenticate_user!

  # GET /steps
  # GET /steps.json
  def index
    @steps = Step.all
  end

  # GET /steps/1
  # GET /steps/1.json
  def show
  end

  # GET /steps/new
  def new
    @step = Step.new
  end

  # GET /steps/1/edit
  def edit
  end

  # POST /steps
  # POST /steps.json
  def create
    @step = Step.new(step_params)

    respond_to do |format|
      if @step.save
        format.html { redirect_to @step, notice: 'Step was successfully created.' }
        format.json { render :show, status: :created, location: @step }
      else
        format.html { render :new }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /steps/1
  # PATCH/PUT /steps/1.json
  def update
    respond_to do |format|
      if @step.update(step_params)
        format.html { redirect_to @step, notice: 'Step was successfully updated.' }
        format.json { render :show, status: :ok, location: @step }
      else
        format.html { render :edit }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /steps/1
  # DELETE /steps/1.json
  def destroy
    @step.destroy
    respond_to do |format|
      format.html { redirect_to steps_url, notice: 'Step was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_step
      @step = Step.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def step_params
      params.require(:step).permit(:sequence, :planstep, :plan_id)
    end
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/steps/_form.html.erb
<%= simple_form_for(@step) do |f| %>
<%= f.input :sequence , label: 'Sequence', hint: 'Integer please', placeholder: '0', required: true %>
    <%= f.input :planstep , label: 'Step details', hint: 'Step info', required: true %>
    <%= f.association :plan %>
    <%= f.button :submit %>
<% end %>

app/views/steps/edit.html.erb
<h1>Editing step</h1>

<%= render 'form' %>

<%= link_to 'Show', @step %> |
<%= link_to 'Back', steps_path %>

app/views/steps/index.html.erb
<h1>Listing steps</h1>

<table>
  <thead>
    <tr>
      <th>Sequence</th>
      <th>Planstep</th>
      <th>Plan</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @steps.each do |step| %>
      <tr>
        <td><%= step.sequence %></td>
        <td><%= step.planstep %></td>
        <td><%= step.plan_id %></td>
        <td><%= link_to 'Show', step %></td>
        <td><%= link_to 'Edit', edit_step_path(step) %></td>
        <td><%= link_to 'Destroy', step, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Step', new_step_path %>

app/views/steps/new.html.erb
<h1>New step</h1>

<%= render 'form' %>

<%= link_to 'Back', steps_path %>

app/views/steps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sequence:</strong>
  <%= @step.sequence %>
</p>

<p>
  <strong>Planstep:</strong>
  <%= @step.planstep %>
</p>

<p>
  <strong>Plan:</strong>
  <%= @step.plan_id %>
</p>

<%= link_to 'Edit', edit_step_path(@step) %> |
<%= link_to 'Back', steps_path %>