config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :users

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :steps
  resources :comments

  resources :plans do
      member do
        get :add_to_calendar
        put :increase_popularity, as: :increase_popularity_of
      end
  end      
  

  get 'pages/info'
  get '/about'    => 'high_voltage/pages#show', id: 'about'
  get '/contact'  => 'high_voltage/pages#show', id: 'contact'
  get '/privacy'  => 'high_voltage/pages#show', id: 'privacy'
  get '/terms'    => 'high_voltage/pages#show', id: 'terms'
  get '/home', to: redirect('/')

  root :to => redirect('/plans')

end

app/views/layouts/_navbar.html.erb
   <!-- Fixed navbar -->
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to site_name, site_url, :class => "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav pull-right">
          <!-- <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li> -->
          <li class="<%= 'active' if current_page?(plans_path) %>"><%= link_to "Browse", plans_path %></li>
          <li class="<%= 'active' if current_page?(new_plan_path) %>"><%= link_to "Create", new_plan_path %></li>
          <li class="<%= 'active' if current_page?(about_path) %>"><%= link_to "About", about_path %></li>
          <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Categories<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li class="divider"></li>
              <li><a href="#">One more separated link</a></li>
              </ul>
          </li>

          <li>
            <%= form_tag plans_path, :method => :get, class: 'navbar-form navbar-left', role: 'search' do %>
              <div class="form-group">
                <%= text_field_tag :search, params[:search],  placeholder: "Search", class: "form-control" %>
                <%= submit_tag "Search", :name => nil, class:'btn btn-default' %>
              </div>
            <% end %>
          </li>
      </ul>
    </div>
  </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="description" content="<%= meta_description %>">
  <meta name="author" content="<%= meta_author %>">
  <meta name="Keywords" content="<%= meta_keywords %>">
  <%= csrf_meta_tags %>
  <title><%= full_title(yield(:title)) %></title>
  <!-- <link rel="stylesheet" href="/css/bootstrap.css"> -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :defaults, "nested_form" %>
  <style type="text/css"> 
     @font-face {   font-family: 'Glyphicons Halflings';   
     src: url('../fonts/glyphicons-halflings-regular.eot');   
     src: url('../fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'), 
     url('../fonts/glyphicons-halflings-regular.woff') format('woff'),  
     url('../fonts/glyphicons-halflings-regular.ttf') format('truetype'), 
     url('../fonts/glyphicons-halflings-regular.svg#glyphicons-halflingsregular') format('svg'); } 
  </style>

  <!-- flatty -->
    <!-- Bootstrap core CSS -->
    <!-- Custom styles for this template -->
    <!-- Fonts from Google Fonts -->
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,900' rel='stylesheet' type='text/css'>
    
</head>
<body>
  <%= render 'layouts/navbar' %>
 

  <% if current_page?(root_path) %>
    <% if content_for?(:jumbotron) %>
      <div class="jumbotron">
        <div class="container">
          <%= yield :jumbotron %>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="container">
  <% end %>
  
  <%= yield %>

  <footer>
    <hr>
      <p class="pull-right">
        <%= link_to '<span class="glyphicon-class glyphicon glyphicon-chevron-up"></span> Back to top'.html_safe, '#Top' %>
      </p>
      <p>
        &copy; <%= Time.now.year %> <%= site_name %> 
        &bull;
        <%= link_to "Privacy", privacy_path %></li>
        &bull;
        <%= link_to "Terms", terms_path %></li>
      </p>
    </footer>
  </div> <!-- /container -->
</body>
</html>